### ISSUE TITLE
希望后续能支持自定义快捷键

### ISSUE THREAD

**Issue by QQQOrange** [Lizhen0628/siyuan-ai#1]
就不知道怎么触发功能

**Comment by QQQOrange** [comment]
重启思源就出现了，希望后续能支持自定义快捷键

**Comment by Lizhen0628** [comment]
是指打开prompt对话框的快捷键吗?

**Comment by QQQOrange** [comment]
> 是指打开prompt对话框的快捷键吗?

是的是的，就按一下快捷键，它就直接出来了。

**Comment by Lizhen0628** [comment]
prompt 对胡a

> > 是指打开prompt对话框的快捷键吗?
> 
> 是的是的，就按一下快捷键，它就直接出来了。

ppromt 对话框需要有一个上下文，而这个上下文就是用鼠标选中的内容。
但是，当前siyuan笔记使用快捷键时，无法获取选中文本。

**Comment by QQQOrange** [comment]
> prompt 对胡a
> 
> > > 是指打开prompt对话框的快捷键吗?
> > 
> > 
> > 是的是的，就按一下快捷键，它就直接出来了。
> 
> ppromt 对话框需要有一个上下文，而这个上下文就是用鼠标选中的内容。 但是，当前siyuan笔记使用快捷键时，无法获取选中文本。

好吧，直接尬住了

**Comment by pisceswb** [comment]
请问大佬能否为“文本生成”功能添加快捷键？ @Lizhen0628
