### ISSUE TITLE
希望支持gpt的多种模型，例如gpt4-0125-preview

### ISSUE THREAD

**Issue by QQQOrange** [Lizhen0628/siyuan-ai#2]
希望支持gpt的多种模型，例如gpt4-0125-preview

**Comment by Lizhen0628** [comment]
当前后台调用的就是gpt-4-0125-preview

**Comment by QQQOrange** [comment]
> 当前后台调用的就是gpt-4-0125-preview

主要是举例子，以这个为例，GPT4还有其他的模型的。

**Comment by Lizhen0628** [comment]
> > 当前后台调用的就是gpt-4-0125-preview
> 
> 主要是举例子，以这个为例，GPT4还有其他的模型的。

模型和api base 绑定，担心用户填入了api base不支持的模型，会引起异常。

**Comment by QQQOrange** [comment]
> > > 当前后台调用的就是gpt-4-0125-preview
> > 
> > 
> > 主要是举例子，以这个为例，GPT4还有其他的模型的。
> 
> 模型和api base 绑定，担心用户填入了api base不支持的模型，会引起异常。

哦哦

**Comment by Lizhen0628** [comment]
> > 当前后台调用的就是gpt-4-0125-preview
> 
> 主要是举例子，以这个为例，GPT4还有其他的模型的。

已支持，更新插件到最新版本即可使用。
