### ISSUE TITLE
支持自定义与保存模型名

### ISSUE THREAD

**Issue by TCOTC** [Lizhen0628/siyuan-ai#4]
#2 的拓展

**Comment by Lizhen0628** [comment]
从自定义模型会增加普通用户的使用成本考虑，暂不支持自定义模型名称。

**Comment by TCOTC** [comment]
主要是，普通用户也用不上自定义，需要自定义的也不是普通用户了，不支持自定义反而增加了高级用户的使用成本，因为要自己改插件
