### ISSUE TITLE
API 基础地址 无法更改

### ISSUE THREAD

**Issue by TCOTC** [Lizhen0628/siyuan-ai#5]
刚开始填错了，但后面发现无论怎样改都还是请求同一个地址：

![image](https://github.com/Lizhen0628/siyuan-ai/assets/78434827/c7cef0d2-a54f-4e47-bd3d-f221fcb5ec0a)

**Comment by Lizhen0628** [comment]
> 刚开始填错了，但后面发现无论怎样改都还是请求同一个地址：
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/323481101-c7cef0d2-a54f-4e47-bd3d-f221fcb5ec0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjAzNzEsIm5iZiI6MTcxMzQyMDA3MSwicGF0aCI6Ii83ODQzNDgyNy8zMjM0ODExMDEtYzdjZWYwZDItYTU0Zi00ZTQ3LWJkM2QtZjIyMWZjYjVlYzBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA2MDExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkN2NlMjRlMTc0NmEwZGE5YTQ5NzVhOTU2OGIwY2JhYjIyYWIxODRjY2FiMTU0YWE4ZTdiMTVmNGNjN2FjYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VQ0uX4mMyemsREVIHFpgGENqt5Wed66-JhYxLgNtmeI)

重新在设置界面填入地址试一下呢

**Comment by TCOTC** [comment]
改来改去都没用，最后是重启思源才生效了

**Comment by Lizhen0628** [comment]
已修复
